package com.crm.mapper;

import com.crm.entity.CustomerPlan;
import com.crm.entity.CustomerPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_plan
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    long countByExample(CustomerPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_plan
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    int deleteByExample(CustomerPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_plan
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    int deleteByPrimaryKey(Integer cpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_plan
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    int insert(CustomerPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_plan
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    int insertSelective(CustomerPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_plan
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    List<CustomerPlan> selectByExample(CustomerPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_plan
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    CustomerPlan selectByPrimaryKey(Integer cpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_plan
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") CustomerPlan record, @Param("example") CustomerPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_plan
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    int updateByExample(@Param("record") CustomerPlan record, @Param("example") CustomerPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_plan
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    int updateByPrimaryKeySelective(CustomerPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_plan
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    int updateByPrimaryKey(CustomerPlan record);
}