package com.crm.mapper;

import com.crm.entity.Customer;
import com.crm.entity.CustomerExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CustomerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	long countByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	int deleteByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	int insert(Customer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	int insertSelective(Customer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	List<Customer> selectByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);
	
	/**
	 * 根据客户id查询出每个客户对应的客户联系人的完整信息
	 * @return 查询到的包含客户联系人信息的客户信息
	 */
	List<Customer> selectCustomerAndContact(@Param("uId") Integer uId);
	
	/**
	 * 根据分组条件查询统计图信息
	 * select count(cus.cus_id) as 'number',cus.cus_grade as 'grade' 
	 * from customer cus
	 * group by cus.cus_grade
	 */
	List<Map<String, Object>> customerreport(@Param("pfreport") String pfreport);
	
}