package com.crm.entity;

public class CustomerContact {
	
	private String cusName;
	
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_contact.cusCon_id
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	private Integer cusconId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_contact.cus_id
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	private Integer cusId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_contact.cusCon_name
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	private String cusconName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_contact.cusCon_sex
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	private Integer cusconSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_contact.cusCon_position
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	private String cusconPosition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_contact.cusCon_officePhone
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	private String cusconOfficephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_contact.cusCon_phone
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	private String cusconPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_contact.cusCon_notes
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	private String cusconNotes;
	
	/**
	 * 客户名
	 * @return
	 */
	public String getCusName() {
		return cusName;
	}

	public void setCusName(String cusName) {
		this.cusName = cusName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_contact.cusCon_id
	 * @return  the value of customer_contact.cusCon_id
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	public Integer getCusconId() {
		return cusconId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_contact.cusCon_id
	 * @param cusconId  the value for customer_contact.cusCon_id
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	public void setCusconId(Integer cusconId) {
		this.cusconId = cusconId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_contact.cus_id
	 * @return  the value of customer_contact.cus_id
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	public Integer getCusId() {
		return cusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_contact.cus_id
	 * @param cusId  the value for customer_contact.cus_id
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	public void setCusId(Integer cusId) {
		this.cusId = cusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_contact.cusCon_name
	 * @return  the value of customer_contact.cusCon_name
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	public String getCusconName() {
		return cusconName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_contact.cusCon_name
	 * @param cusconName  the value for customer_contact.cusCon_name
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	public void setCusconName(String cusconName) {
		this.cusconName = cusconName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_contact.cusCon_sex
	 * @return  the value of customer_contact.cusCon_sex
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	public Integer getCusconSex() {
		return cusconSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_contact.cusCon_sex
	 * @param cusconSex  the value for customer_contact.cusCon_sex
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	public void setCusconSex(Integer cusconSex) {
		this.cusconSex = cusconSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_contact.cusCon_position
	 * @return  the value of customer_contact.cusCon_position
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	public String getCusconPosition() {
		return cusconPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_contact.cusCon_position
	 * @param cusconPosition  the value for customer_contact.cusCon_position
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	public void setCusconPosition(String cusconPosition) {
		this.cusconPosition = cusconPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_contact.cusCon_officePhone
	 * @return  the value of customer_contact.cusCon_officePhone
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	public String getCusconOfficephone() {
		return cusconOfficephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_contact.cusCon_officePhone
	 * @param cusconOfficephone  the value for customer_contact.cusCon_officePhone
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	public void setCusconOfficephone(String cusconOfficephone) {
		this.cusconOfficephone = cusconOfficephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_contact.cusCon_phone
	 * @return  the value of customer_contact.cusCon_phone
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	public String getCusconPhone() {
		return cusconPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_contact.cusCon_phone
	 * @param cusconPhone  the value for customer_contact.cusCon_phone
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	public void setCusconPhone(String cusconPhone) {
		this.cusconPhone = cusconPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_contact.cusCon_notes
	 * @return  the value of customer_contact.cusCon_notes
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	public String getCusconNotes() {
		return cusconNotes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_contact.cusCon_notes
	 * @param cusconNotes  the value for customer_contact.cusCon_notes
	 * @mbg.generated  Mon May 04 13:49:33 CST 2020
	 */
	public void setCusconNotes(String cusconNotes) {
		this.cusconNotes = cusconNotes;
	}

	/**
	 * CusName
	 * @return
	 */
//	public String getCusName() {
//		return cusName;
//	}
//
//	public void setCusName(String cusName) {
//		this.cusName = cusName;
//	}
	
	

	@Override
	public String toString() {
		return "CustomerContact [cusconId=" + cusconId + ", cusId=" + cusId + ", cusconName="
				+ cusconName + ", cusconSex=" + cusconSex + ", cusconPosition=" + cusconPosition
				+ ", cusconOfficephone=" + cusconOfficephone + ", cusconPhone=" + cusconPhone + ", cusconNotes="
				+ cusconNotes + "]";
	}
}