package com.crm.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class CustomerPlan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_plan.cp_id
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    private Integer cpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_plan.cp_date
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy/MM/dd",timezone="GMT+8")
    private Date cpDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_plan.cp_content
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    private String cpContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_plan.cp_plancase
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    private String cpPlancase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_plan.cp_plandate
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy/MM/dd",timezone="GMT+8")
    private Date cpPlandate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_plan.sc_id
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    private Integer scId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_plan.cp_id
     *
     * @return the value of customer_plan.cp_id
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public Integer getCpId() {
        return cpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_plan.cp_id
     *
     * @param cpId the value for customer_plan.cp_id
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setCpId(Integer cpId) {
        this.cpId = cpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_plan.cp_date
     *
     * @return the value of customer_plan.cp_date
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public Date getCpDate() {
        return cpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_plan.cp_date
     *
     * @param cpDate the value for customer_plan.cp_date
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setCpDate(Date cpDate) {
        this.cpDate = cpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_plan.cp_content
     *
     * @return the value of customer_plan.cp_content
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public String getCpContent() {
        return cpContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_plan.cp_content
     *
     * @param cpContent the value for customer_plan.cp_content
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setCpContent(String cpContent) {
        this.cpContent = cpContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_plan.cp_plancase
     *
     * @return the value of customer_plan.cp_plancase
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public String getCpPlancase() {
        return cpPlancase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_plan.cp_plancase
     *
     * @param cpPlancase the value for customer_plan.cp_plancase
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setCpPlancase(String cpPlancase) {
        this.cpPlancase = cpPlancase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_plan.cp_plandate
     *
     * @return the value of customer_plan.cp_plandate
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public Date getCpPlandate() {
        return cpPlandate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_plan.cp_plandate
     *
     * @param cpPlandate the value for customer_plan.cp_plandate
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setCpPlandate(Date cpPlandate) {
        this.cpPlandate = cpPlandate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_plan.sc_id
     *
     * @return the value of customer_plan.sc_id
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public Integer getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_plan.sc_id
     *
     * @param scId the value for customer_plan.sc_id
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setScId(Integer scId) {
        this.scId = scId;
    }
}