package com.crm.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class SaleChance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_id
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    private Integer scId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_cusname
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    private String scCusname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_comming
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    private String scComming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_name
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    private String scName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_phone
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    private String scPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_success
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    private String scSuccess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_message
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    private String scMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_desc
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    private String scDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_user
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    private String scUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_createtime
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy/MM/dd",timezone="GMT+8")
    private Date scCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_giveuser
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    private String scGiveuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_givetime
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy/MM/dd",timezone="GMT+8")
    private Date scGivetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_status
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    private Integer scStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_id
     *
     * @return the value of sale_chance.sc_id
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public Integer getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_id
     *
     * @param scId the value for sale_chance.sc_id
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setScId(Integer scId) {
        this.scId = scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_cusname
     *
     * @return the value of sale_chance.sc_cusname
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public String getScCusname() {
        return scCusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_cusname
     *
     * @param scCusname the value for sale_chance.sc_cusname
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setScCusname(String scCusname) {
        this.scCusname = scCusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_comming
     *
     * @return the value of sale_chance.sc_comming
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public String getScComming() {
        return scComming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_comming
     *
     * @param scComming the value for sale_chance.sc_comming
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setScComming(String scComming) {
        this.scComming = scComming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_name
     *
     * @return the value of sale_chance.sc_name
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public String getScName() {
        return scName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_name
     *
     * @param scName the value for sale_chance.sc_name
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setScName(String scName) {
        this.scName = scName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_phone
     *
     * @return the value of sale_chance.sc_phone
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public String getScPhone() {
        return scPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_phone
     *
     * @param scPhone the value for sale_chance.sc_phone
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setScPhone(String scPhone) {
        this.scPhone = scPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_success
     *
     * @return the value of sale_chance.sc_success
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public String getScSuccess() {
        return scSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_success
     *
     * @param scSuccess the value for sale_chance.sc_success
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setScSuccess(String scSuccess) {
        this.scSuccess = scSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_message
     *
     * @return the value of sale_chance.sc_message
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public String getScMessage() {
        return scMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_message
     *
     * @param scMessage the value for sale_chance.sc_message
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setScMessage(String scMessage) {
        this.scMessage = scMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_desc
     *
     * @return the value of sale_chance.sc_desc
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public String getScDesc() {
        return scDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_desc
     *
     * @param scDesc the value for sale_chance.sc_desc
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setScDesc(String scDesc) {
        this.scDesc = scDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_user
     *
     * @return the value of sale_chance.sc_user
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public String getScUser() {
        return scUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_user
     *
     * @param scUser the value for sale_chance.sc_user
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setScUser(String scUser) {
        this.scUser = scUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_createtime
     *
     * @return the value of sale_chance.sc_createtime
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public Date getScCreatetime() {
        return scCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_createtime
     *
     * @param scCreatetime the value for sale_chance.sc_createtime
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setScCreatetime(Date scCreatetime) {
        this.scCreatetime = scCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_giveuser
     *
     * @return the value of sale_chance.sc_giveuser
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public String getScGiveuser() {
        return scGiveuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_giveuser
     *
     * @param scGiveuser the value for sale_chance.sc_giveuser
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setScGiveuser(String scGiveuser) {
        this.scGiveuser = scGiveuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_givetime
     *
     * @return the value of sale_chance.sc_givetime
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public Date getScGivetime() {
        return scGivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_givetime
     *
     * @param scGivetime the value for sale_chance.sc_givetime
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setScGivetime(Date scGivetime) {
        this.scGivetime = scGivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_status
     *
     * @return the value of sale_chance.sc_status
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public Integer getScStatus() {
        return scStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_status
     *
     * @param scStatus the value for sale_chance.sc_status
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setScStatus(Integer scStatus) {
        this.scStatus = scStatus;
    }
    
}