package com.crm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SaleChanceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_chance
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_chance
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_chance
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public SaleChanceExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_chance
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andScIdIsNull() {
            addCriterion("sc_id is null");
            return (Criteria) this;
        }

        public Criteria andScIdIsNotNull() {
            addCriterion("sc_id is not null");
            return (Criteria) this;
        }

        public Criteria andScIdEqualTo(Integer value) {
            addCriterion("sc_id =", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotEqualTo(Integer value) {
            addCriterion("sc_id <>", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdGreaterThan(Integer value) {
            addCriterion("sc_id >", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sc_id >=", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdLessThan(Integer value) {
            addCriterion("sc_id <", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdLessThanOrEqualTo(Integer value) {
            addCriterion("sc_id <=", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdIn(List<Integer> values) {
            addCriterion("sc_id in", values, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotIn(List<Integer> values) {
            addCriterion("sc_id not in", values, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdBetween(Integer value1, Integer value2) {
            addCriterion("sc_id between", value1, value2, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sc_id not between", value1, value2, "scId");
            return (Criteria) this;
        }

        public Criteria andScCusnameIsNull() {
            addCriterion("sc_cusname is null");
            return (Criteria) this;
        }

        public Criteria andScCusnameIsNotNull() {
            addCriterion("sc_cusname is not null");
            return (Criteria) this;
        }

        public Criteria andScCusnameEqualTo(String value) {
            addCriterion("sc_cusname =", value, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameNotEqualTo(String value) {
            addCriterion("sc_cusname <>", value, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameGreaterThan(String value) {
            addCriterion("sc_cusname >", value, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameGreaterThanOrEqualTo(String value) {
            addCriterion("sc_cusname >=", value, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameLessThan(String value) {
            addCriterion("sc_cusname <", value, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameLessThanOrEqualTo(String value) {
            addCriterion("sc_cusname <=", value, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameLike(String value) {
            addCriterion("sc_cusname like", value, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameNotLike(String value) {
            addCriterion("sc_cusname not like", value, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameIn(List<String> values) {
            addCriterion("sc_cusname in", values, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameNotIn(List<String> values) {
            addCriterion("sc_cusname not in", values, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameBetween(String value1, String value2) {
            addCriterion("sc_cusname between", value1, value2, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameNotBetween(String value1, String value2) {
            addCriterion("sc_cusname not between", value1, value2, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCommingIsNull() {
            addCriterion("sc_comming is null");
            return (Criteria) this;
        }

        public Criteria andScCommingIsNotNull() {
            addCriterion("sc_comming is not null");
            return (Criteria) this;
        }

        public Criteria andScCommingEqualTo(String value) {
            addCriterion("sc_comming =", value, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingNotEqualTo(String value) {
            addCriterion("sc_comming <>", value, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingGreaterThan(String value) {
            addCriterion("sc_comming >", value, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingGreaterThanOrEqualTo(String value) {
            addCriterion("sc_comming >=", value, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingLessThan(String value) {
            addCriterion("sc_comming <", value, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingLessThanOrEqualTo(String value) {
            addCriterion("sc_comming <=", value, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingLike(String value) {
            addCriterion("sc_comming like", value, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingNotLike(String value) {
            addCriterion("sc_comming not like", value, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingIn(List<String> values) {
            addCriterion("sc_comming in", values, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingNotIn(List<String> values) {
            addCriterion("sc_comming not in", values, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingBetween(String value1, String value2) {
            addCriterion("sc_comming between", value1, value2, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingNotBetween(String value1, String value2) {
            addCriterion("sc_comming not between", value1, value2, "scComming");
            return (Criteria) this;
        }

        public Criteria andScNameIsNull() {
            addCriterion("sc_name is null");
            return (Criteria) this;
        }

        public Criteria andScNameIsNotNull() {
            addCriterion("sc_name is not null");
            return (Criteria) this;
        }

        public Criteria andScNameEqualTo(String value) {
            addCriterion("sc_name =", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameNotEqualTo(String value) {
            addCriterion("sc_name <>", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameGreaterThan(String value) {
            addCriterion("sc_name >", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameGreaterThanOrEqualTo(String value) {
            addCriterion("sc_name >=", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameLessThan(String value) {
            addCriterion("sc_name <", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameLessThanOrEqualTo(String value) {
            addCriterion("sc_name <=", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameLike(String value) {
            addCriterion("sc_name like", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameNotLike(String value) {
            addCriterion("sc_name not like", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameIn(List<String> values) {
            addCriterion("sc_name in", values, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameNotIn(List<String> values) {
            addCriterion("sc_name not in", values, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameBetween(String value1, String value2) {
            addCriterion("sc_name between", value1, value2, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameNotBetween(String value1, String value2) {
            addCriterion("sc_name not between", value1, value2, "scName");
            return (Criteria) this;
        }

        public Criteria andScPhoneIsNull() {
            addCriterion("sc_phone is null");
            return (Criteria) this;
        }

        public Criteria andScPhoneIsNotNull() {
            addCriterion("sc_phone is not null");
            return (Criteria) this;
        }

        public Criteria andScPhoneEqualTo(String value) {
            addCriterion("sc_phone =", value, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneNotEqualTo(String value) {
            addCriterion("sc_phone <>", value, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneGreaterThan(String value) {
            addCriterion("sc_phone >", value, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("sc_phone >=", value, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneLessThan(String value) {
            addCriterion("sc_phone <", value, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneLessThanOrEqualTo(String value) {
            addCriterion("sc_phone <=", value, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneLike(String value) {
            addCriterion("sc_phone like", value, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneNotLike(String value) {
            addCriterion("sc_phone not like", value, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneIn(List<String> values) {
            addCriterion("sc_phone in", values, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneNotIn(List<String> values) {
            addCriterion("sc_phone not in", values, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneBetween(String value1, String value2) {
            addCriterion("sc_phone between", value1, value2, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneNotBetween(String value1, String value2) {
            addCriterion("sc_phone not between", value1, value2, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScSuccessIsNull() {
            addCriterion("sc_success is null");
            return (Criteria) this;
        }

        public Criteria andScSuccessIsNotNull() {
            addCriterion("sc_success is not null");
            return (Criteria) this;
        }

        public Criteria andScSuccessEqualTo(String value) {
            addCriterion("sc_success =", value, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessNotEqualTo(String value) {
            addCriterion("sc_success <>", value, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessGreaterThan(String value) {
            addCriterion("sc_success >", value, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessGreaterThanOrEqualTo(String value) {
            addCriterion("sc_success >=", value, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessLessThan(String value) {
            addCriterion("sc_success <", value, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessLessThanOrEqualTo(String value) {
            addCriterion("sc_success <=", value, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessLike(String value) {
            addCriterion("sc_success like", value, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessNotLike(String value) {
            addCriterion("sc_success not like", value, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessIn(List<String> values) {
            addCriterion("sc_success in", values, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessNotIn(List<String> values) {
            addCriterion("sc_success not in", values, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessBetween(String value1, String value2) {
            addCriterion("sc_success between", value1, value2, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessNotBetween(String value1, String value2) {
            addCriterion("sc_success not between", value1, value2, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScMessageIsNull() {
            addCriterion("sc_message is null");
            return (Criteria) this;
        }

        public Criteria andScMessageIsNotNull() {
            addCriterion("sc_message is not null");
            return (Criteria) this;
        }

        public Criteria andScMessageEqualTo(String value) {
            addCriterion("sc_message =", value, "scMessage");
            return (Criteria) this;
        }

        public Criteria andScMessageNotEqualTo(String value) {
            addCriterion("sc_message <>", value, "scMessage");
            return (Criteria) this;
        }

        public Criteria andScMessageGreaterThan(String value) {
            addCriterion("sc_message >", value, "scMessage");
            return (Criteria) this;
        }

        public Criteria andScMessageGreaterThanOrEqualTo(String value) {
            addCriterion("sc_message >=", value, "scMessage");
            return (Criteria) this;
        }

        public Criteria andScMessageLessThan(String value) {
            addCriterion("sc_message <", value, "scMessage");
            return (Criteria) this;
        }

        public Criteria andScMessageLessThanOrEqualTo(String value) {
            addCriterion("sc_message <=", value, "scMessage");
            return (Criteria) this;
        }

        public Criteria andScMessageLike(String value) {
            addCriterion("sc_message like", value, "scMessage");
            return (Criteria) this;
        }

        public Criteria andScMessageNotLike(String value) {
            addCriterion("sc_message not like", value, "scMessage");
            return (Criteria) this;
        }

        public Criteria andScMessageIn(List<String> values) {
            addCriterion("sc_message in", values, "scMessage");
            return (Criteria) this;
        }

        public Criteria andScMessageNotIn(List<String> values) {
            addCriterion("sc_message not in", values, "scMessage");
            return (Criteria) this;
        }

        public Criteria andScMessageBetween(String value1, String value2) {
            addCriterion("sc_message between", value1, value2, "scMessage");
            return (Criteria) this;
        }

        public Criteria andScMessageNotBetween(String value1, String value2) {
            addCriterion("sc_message not between", value1, value2, "scMessage");
            return (Criteria) this;
        }

        public Criteria andScDescIsNull() {
            addCriterion("sc_desc is null");
            return (Criteria) this;
        }

        public Criteria andScDescIsNotNull() {
            addCriterion("sc_desc is not null");
            return (Criteria) this;
        }

        public Criteria andScDescEqualTo(String value) {
            addCriterion("sc_desc =", value, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescNotEqualTo(String value) {
            addCriterion("sc_desc <>", value, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescGreaterThan(String value) {
            addCriterion("sc_desc >", value, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescGreaterThanOrEqualTo(String value) {
            addCriterion("sc_desc >=", value, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescLessThan(String value) {
            addCriterion("sc_desc <", value, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescLessThanOrEqualTo(String value) {
            addCriterion("sc_desc <=", value, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescLike(String value) {
            addCriterion("sc_desc like", value, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescNotLike(String value) {
            addCriterion("sc_desc not like", value, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescIn(List<String> values) {
            addCriterion("sc_desc in", values, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescNotIn(List<String> values) {
            addCriterion("sc_desc not in", values, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescBetween(String value1, String value2) {
            addCriterion("sc_desc between", value1, value2, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescNotBetween(String value1, String value2) {
            addCriterion("sc_desc not between", value1, value2, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScUserIsNull() {
            addCriterion("sc_user is null");
            return (Criteria) this;
        }

        public Criteria andScUserIsNotNull() {
            addCriterion("sc_user is not null");
            return (Criteria) this;
        }

        public Criteria andScUserEqualTo(String value) {
            addCriterion("sc_user =", value, "scUser");
            return (Criteria) this;
        }

        public Criteria andScUserNotEqualTo(String value) {
            addCriterion("sc_user <>", value, "scUser");
            return (Criteria) this;
        }

        public Criteria andScUserGreaterThan(String value) {
            addCriterion("sc_user >", value, "scUser");
            return (Criteria) this;
        }

        public Criteria andScUserGreaterThanOrEqualTo(String value) {
            addCriterion("sc_user >=", value, "scUser");
            return (Criteria) this;
        }

        public Criteria andScUserLessThan(String value) {
            addCriterion("sc_user <", value, "scUser");
            return (Criteria) this;
        }

        public Criteria andScUserLessThanOrEqualTo(String value) {
            addCriterion("sc_user <=", value, "scUser");
            return (Criteria) this;
        }

        public Criteria andScUserLike(String value) {
            addCriterion("sc_user like", value, "scUser");
            return (Criteria) this;
        }

        public Criteria andScUserNotLike(String value) {
            addCriterion("sc_user not like", value, "scUser");
            return (Criteria) this;
        }

        public Criteria andScUserIn(List<String> values) {
            addCriterion("sc_user in", values, "scUser");
            return (Criteria) this;
        }

        public Criteria andScUserNotIn(List<String> values) {
            addCriterion("sc_user not in", values, "scUser");
            return (Criteria) this;
        }

        public Criteria andScUserBetween(String value1, String value2) {
            addCriterion("sc_user between", value1, value2, "scUser");
            return (Criteria) this;
        }

        public Criteria andScUserNotBetween(String value1, String value2) {
            addCriterion("sc_user not between", value1, value2, "scUser");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeIsNull() {
            addCriterion("sc_createtime is null");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeIsNotNull() {
            addCriterion("sc_createtime is not null");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeEqualTo(Date value) {
            addCriterion("sc_createtime =", value, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeNotEqualTo(Date value) {
            addCriterion("sc_createtime <>", value, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeGreaterThan(Date value) {
            addCriterion("sc_createtime >", value, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sc_createtime >=", value, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeLessThan(Date value) {
            addCriterion("sc_createtime <", value, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("sc_createtime <=", value, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeIn(List<Date> values) {
            addCriterion("sc_createtime in", values, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeNotIn(List<Date> values) {
            addCriterion("sc_createtime not in", values, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeBetween(Date value1, Date value2) {
            addCriterion("sc_createtime between", value1, value2, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("sc_createtime not between", value1, value2, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScGiveuserIsNull() {
            addCriterion("sc_giveuser is null");
            return (Criteria) this;
        }

        public Criteria andScGiveuserIsNotNull() {
            addCriterion("sc_giveuser is not null");
            return (Criteria) this;
        }

        public Criteria andScGiveuserEqualTo(String value) {
            addCriterion("sc_giveuser =", value, "scGiveuser");
            return (Criteria) this;
        }

        public Criteria andScGiveuserNotEqualTo(String value) {
            addCriterion("sc_giveuser <>", value, "scGiveuser");
            return (Criteria) this;
        }

        public Criteria andScGiveuserGreaterThan(String value) {
            addCriterion("sc_giveuser >", value, "scGiveuser");
            return (Criteria) this;
        }

        public Criteria andScGiveuserGreaterThanOrEqualTo(String value) {
            addCriterion("sc_giveuser >=", value, "scGiveuser");
            return (Criteria) this;
        }

        public Criteria andScGiveuserLessThan(String value) {
            addCriterion("sc_giveuser <", value, "scGiveuser");
            return (Criteria) this;
        }

        public Criteria andScGiveuserLessThanOrEqualTo(String value) {
            addCriterion("sc_giveuser <=", value, "scGiveuser");
            return (Criteria) this;
        }

        public Criteria andScGiveuserLike(String value) {
            addCriterion("sc_giveuser like", value, "scGiveuser");
            return (Criteria) this;
        }

        public Criteria andScGiveuserNotLike(String value) {
            addCriterion("sc_giveuser not like", value, "scGiveuser");
            return (Criteria) this;
        }

        public Criteria andScGiveuserIn(List<String> values) {
            addCriterion("sc_giveuser in", values, "scGiveuser");
            return (Criteria) this;
        }

        public Criteria andScGiveuserNotIn(List<String> values) {
            addCriterion("sc_giveuser not in", values, "scGiveuser");
            return (Criteria) this;
        }

        public Criteria andScGiveuserBetween(String value1, String value2) {
            addCriterion("sc_giveuser between", value1, value2, "scGiveuser");
            return (Criteria) this;
        }

        public Criteria andScGiveuserNotBetween(String value1, String value2) {
            addCriterion("sc_giveuser not between", value1, value2, "scGiveuser");
            return (Criteria) this;
        }

        public Criteria andScGivetimeIsNull() {
            addCriterion("sc_givetime is null");
            return (Criteria) this;
        }

        public Criteria andScGivetimeIsNotNull() {
            addCriterion("sc_givetime is not null");
            return (Criteria) this;
        }

        public Criteria andScGivetimeEqualTo(Date value) {
            addCriterion("sc_givetime =", value, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeNotEqualTo(Date value) {
            addCriterion("sc_givetime <>", value, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeGreaterThan(Date value) {
            addCriterion("sc_givetime >", value, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sc_givetime >=", value, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeLessThan(Date value) {
            addCriterion("sc_givetime <", value, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeLessThanOrEqualTo(Date value) {
            addCriterion("sc_givetime <=", value, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeIn(List<Date> values) {
            addCriterion("sc_givetime in", values, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeNotIn(List<Date> values) {
            addCriterion("sc_givetime not in", values, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeBetween(Date value1, Date value2) {
            addCriterion("sc_givetime between", value1, value2, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeNotBetween(Date value1, Date value2) {
            addCriterion("sc_givetime not between", value1, value2, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScStatusIsNull() {
            addCriterion("sc_status is null");
            return (Criteria) this;
        }

        public Criteria andScStatusIsNotNull() {
            addCriterion("sc_status is not null");
            return (Criteria) this;
        }

        public Criteria andScStatusEqualTo(Integer value) {
            addCriterion("sc_status =", value, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusNotEqualTo(Integer value) {
            addCriterion("sc_status <>", value, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusGreaterThan(Integer value) {
            addCriterion("sc_status >", value, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("sc_status >=", value, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusLessThan(Integer value) {
            addCriterion("sc_status <", value, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusLessThanOrEqualTo(Integer value) {
            addCriterion("sc_status <=", value, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusIn(List<Integer> values) {
            addCriterion("sc_status in", values, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusNotIn(List<Integer> values) {
            addCriterion("sc_status not in", values, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusBetween(Integer value1, Integer value2) {
            addCriterion("sc_status between", value1, value2, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("sc_status not between", value1, value2, "scStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_chance
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 31 14:04:49 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_chance
     *
     * @mbg.generated Tue Mar 31 14:04:49 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}