package com.crm.entity;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.u_id
	 * @mbg.generated  Tue Mar 31 14:04:49 CST 2020
	 */
	private Integer uId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.u_name
	 * @mbg.generated  Tue Mar 31 14:04:49 CST 2020
	 */
	private String uName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.u_password
	 * @mbg.generated  Tue Mar 31 14:04:49 CST 2020
	 */
	private String uPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.r_id
	 * @mbg.generated  Tue Mar 31 14:04:49 CST 2020
	 */
	private Integer rId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.u_id
	 * @return  the value of user.u_id
	 * @mbg.generated  Tue Mar 31 14:04:49 CST 2020
	 */
	public Integer getuId() {
		return uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.u_id
	 * @param uId  the value for user.u_id
	 * @mbg.generated  Tue Mar 31 14:04:49 CST 2020
	 */
	public void setuId(Integer uId) {
		this.uId = uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.u_name
	 * @return  the value of user.u_name
	 * @mbg.generated  Tue Mar 31 14:04:49 CST 2020
	 */
	public String getuName() {
		return uName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.u_name
	 * @param uName  the value for user.u_name
	 * @mbg.generated  Tue Mar 31 14:04:49 CST 2020
	 */
	public void setuName(String uName) {
		this.uName = uName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.u_password
	 * @return  the value of user.u_password
	 * @mbg.generated  Tue Mar 31 14:04:49 CST 2020
	 */
	public String getuPassword() {
		return uPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.u_password
	 * @param uPassword  the value for user.u_password
	 * @mbg.generated  Tue Mar 31 14:04:49 CST 2020
	 */
	public void setuPassword(String uPassword) {
		this.uPassword = uPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.r_id
	 * @return  the value of user.r_id
	 * @mbg.generated  Tue Mar 31 14:04:49 CST 2020
	 */
	public Integer getrId() {
		return rId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.r_id
	 * @param rId  the value for user.r_id
	 * @mbg.generated  Tue Mar 31 14:04:49 CST 2020
	 */
	public void setrId(Integer rId) {
		this.rId = rId;
	}
}